/**
 * Shared metadata helpers.
 *
 * Two Next behaviours make this worth centralising:
 *
 * 1. Metadata is INHERITED down the segment tree. A `canonical` set in the root
 *    layout would therefore apply to every page that doesn't override it —
 *    which is exactly the bug the live site has today, where index.html
 *    hardcodes a canonical pointing at the homepage and every URL declares
 *    itself a duplicate of "/". So the root layout sets no canonical at all,
 *    and every page supplies its own through buildMetadata().
 *
 * 2. Nested metadata objects are merged SHALLOWLY: a page that defines
 *    `openGraph` replaces the root's entire openGraph block, silently dropping
 *    siteName, locale and type. buildMetadata() re-applies the defaults so a
 *    page only has to state what is specific to it.
 */

export const SITE_URL = 'https://www.haelsoftmarketplace.com';
export const SITE_NAME = 'Haelsoft Marketplace';

/**
 * Generated by app/opengraph-image.js. Referenced explicitly because a page
 * that defines `openGraph` replaces the object Next builds from the
 * opengraph-image file convention — the same shallow-merge behaviour this
 * helper exists to work around. Without this, every page that called
 * buildMetadata() silently lost the default social image.
 */
export const DEFAULT_OG_IMAGE = `${SITE_URL}/opengraph-image`;

/**
 * @param {object}  o
 * @param {string}  o.title        page title (goes through the "%s | Haelsoft" template)
 * @param {string}  o.description
 * @param {string}  o.path         canonical path, e.g. "/pricing" or "/courses/foo"
 * @param {string} [o.image]       absolute image URL (R2 thumbnails already are)
 * @param {string} [o.type]        openGraph type; defaults to "website"
 * @param {boolean}[o.noindex]
 * @param {boolean}[o.absoluteTitle] bypass the "%s | Haelsoft" template, for titles
 *                                   that already carry the brand
 */
export function buildMetadata({
  title,
  description,
  path,
  image,
  type = 'website',
  noindex = false,
  absoluteTitle = false,
}) {
  const url = `${SITE_URL}${path}`;
  const resolved = image || DEFAULT_OG_IMAGE;
  const images = [{ url: resolved }];

  return {
    title: absoluteTitle ? { absolute: title } : title,
    description,
    alternates: { canonical: url },
    openGraph: {
      title,
      description,
      url,
      siteName: SITE_NAME,
      type,
      locale: 'en_NG',
      images,
    },
    twitter: {
      // Both the per-page thumbnails and the generated default are wide.
      card: 'summary_large_image',
      title,
      description,
      images,
    },
    ...(noindex && { robots: { index: false, follow: false } }),
  };
}
